# configuration for "non-master" branches
-
version: 1.0.{build}
branches:
  except:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  COVERALLS_TOKEN:
    secure: yQbjLdQV0mU9QgTmlINi4ey+Y+gGaiz/EZqfr/41adeVjgGc9GhgJA3W/FArFAVu
  NUGET_SOURCE: https://www.myget.org/F/dhgms/api/v2/package
  NUGET_APIKEY:
    secure: RErDVlA5kOT7ZT4maCrp4KE73pzZYaMz5T+OrDqRu2AObjUTaNNvTvRwEqlve/O+
  sonarqubeLogin:
    secure: cn/J1/GsOt4dF7zRxdB9ajSk1/UzxYZq0MMLLQPkFA92GtrWIYeiKgrzC2d5z7bq
init:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -ne 'master') {
      $env:localversionsuffix = '-' + $env:APPVEYOR_REPO_BRANCH
    }
before_build:
# If there's a newer build queued for the same PR, cancel this one
# taken from: https://raw.githubusercontent.com/tkelman/numpy/440e81ace36d65a7b62eec1a0460467f3dc97085/appveyor.yml
- ps: |
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
            https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
            Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
build_script:
  - ./build.cmd
artifacts:
  - path: artifacts/*.nupkg
  - path: '**/bin/*'
  - path: '**/*.binlog'
test: off
  on_failure:
  - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

# configuration for "master" branch
-
version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  COVERALLS_TOKEN: ?
    secure: yQbjLdQV0mU9QgTmlINi4ey+Y+gGaiz/EZqfr/41adeVjgGc9GhgJA3W/FArFAVu
  GITHUB_USERNAME:
    secure: ?
  GITHUB_TOKEN:
    secure: ?
  NUGET_SOURCE: https://www.nuget.org/api/v2/package
  NUGET_APIKEY:
    secure: 8GpBZ6IHRM4AV4mP8qCqUgJi0NCHX17OlzbrEZRoDCE0s2ZwXHOeqMfIwrGaakg9
  sonarqubeLogin:
    secure: cn/J1/GsOt4dF7zRxdB9ajSk1/UzxYZq0MMLLQPkFA92GtrWIYeiKgrzC2d5z7bq
init:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -ne 'master') {
      $env:localversionsuffix = '-' + $env:APPVEYOR_REPO_BRANCH
    }
before_build:
# If there's a newer build queued for the same PR, cancel this one
# taken from: https://raw.githubusercontent.com/tkelman/numpy/440e81ace36d65a7b62eec1a0460467f3dc97085/appveyor.yml
- ps: |
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
            https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
            Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
build_script:
  - ./build.cmd
artifacts:
  - path: artifacts/*.nupkg
  - path: '**/bin/*'
  - path: '**/*.binlog'
test: off
  on_failure:
  - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }